version: 2
python:
  install:
    - method: pip
      path: ..
      extra_requirements:
        - sphinx-rtd-theme
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
sphinx:
  configuration: docs/conf.py




