package:
  name: apsis
  version: 0.0.0

about:
  home: https://github.com/alexhsamuel/apsis
  license: BSD
  license_file: LICENSE

source:
  git_rev: 0.0.0
  git_url: https://github.com/alexhsamuel/apsis.git

requirements:
  build:
    - python
  run:
    - jinja2
    - alexhsamuel/ora
    - python
    - pyyaml
    - requests
    - rich
    - conda-forge/sanic >=21.3
    - sqlalchemy
    - ujson

build:
  script: python setup.py install

test:
  imports:
    - apsis

