name: Apsis CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upgrade pip
      run: pip3 install --upgrade pip 'setuptools>=61'

    - name: Install package
      run: pip3 install -e .[dev]

    - name: Install procstar
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "alexhsamuel/procstar"
        latest: true
        fileName: procstar

    - name: Run Python unit tests
      run: pytest test/unit -m "not local_ssh"

    - name: Run Python integration tets
      run: pytest test/int -m "not local_ssh"

